#!/usr/bin/env bash

# Exit immediately if NAPS2 console utility is not found
if ! command -v naps2 &> /dev/null; then
    echo "Error: 'naps2' command not found. Please make sure NAPS2 is installed and in your PATH." >&2
    exit 1
fi

# Check for poppler-utils (pdftotext) to enable pre-OCR detection
if ! command -v pdftotext &> /dev/null; then
    echo "Warning: 'pdftotext' is not installed. Script will not be able to detect pre-existing text layers in PDFs." >&2
fi

# Enable nullglob so unmatched patterns expand to nothing instead of literal strings
shopt -s nullglob

echo "Starting OCR batch processing (PDFs & JPEGs)..."
echo "----------------------------------------"

processed_count=0
skipped_count=0

# Loop through all PDFs and JPEGs in the current directory
for file in *.pdf *.jpg *.jpeg *.JPG *.JPEG *.png *.PNG; do
    # Ensure it is a regular file
    [ -f "$file" ] || continue

    # Prevent processing already OCRed output files generated by this script
    if [[ "$file" == *"_OCRed.pdf" ]]; then
        echo "Skipping already processed file: $file"
        ((skipped_count++))
        continue
    fi

    # Check if a PDF file ALREADY has a searchable text layer before doing anything
    if [[ "$file" == *.pdf ]] && command -v pdftotext &> /dev/null; then
        if pdftotext "$file" - 2>/dev/null | grep -q '[^[:space:]]'; then
            echo "Skipping (Already OCRed / contains text layer): $file"
            ((skipped_count++))
            continue
        fi
    fi

    # Strip extension and append _OCRed.pdf
    output_pdf="${file%.*}_OCRed.pdf"

    # Skip processing if output file already exists to avoid redundant work
    if [ -f "$output_pdf" ]; then
        echo "Skipping (Output file already exists): $output_pdf"
        ((skipped_count++))
        continue
    fi

    echo "Processing: $file -> $output_pdf"
    
    # Execute NAPS2 OCR conversion (works natively for images and PDFs)
    if naps2 console -i "$file" -n 0 -o "$output_pdf" --enableocr; then
        echo "  [OK] Successfully processed: $output_pdf"
        ((processed_count++))
        
        # Verify if OCR text layer was actually created
        if command -v pdftotext &> /dev/null; then
            if ! pdftotext "$output_pdf" - 2>/dev/null | grep -q '[^[:space:]]'; then
                echo "  [WARNING] No searchable text detected in $output_pdf. Image quality or resolution may need adjustment."
            fi
        fi
    else
        echo "  [ERROR] Failed to process $file" >&2
    fi
    
    echo "----------------------------------------"
done

echo "Batch processing finished."
echo "Summary: $processed_count file(s) OCRed, $skipped_count file(s) skipped."

